#!/usr/bin/env python3
"""Stage 3X train/validation target-relation screening.

This worker scores the CPU-screening seed genomes emitted by
``stage3x_parametric_data_space_worker.py``. It is deliberately pre-RL: no
training, no Stage C rows, and no broad GPU dispatch. Its output is a reduced
set of data/feature/preprocessing contracts that are worth considering for SAC
smoke runs.
"""
from __future__ import annotations

import csv
import hashlib
import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from sklearn.feature_selection import mutual_info_regression


ROOT = Path(__file__).resolve().parents[2]
POPULATION_CSV = (
    ROOT
    / "experiments"
    / "stage3x_parametric_data_space"
    / "project3_data_preprocessing_seed_population.csv"
)
OUT_ROOT = ROOT / "experiments" / "stage3x_target_relation_screen"
OUT_JSON = OUT_ROOT / "stage3x_target_relation_screen.json"
OUT_CSV = OUT_ROOT / "stage3x_target_relation_screen.csv"
OUT_MD = OUT_ROOT / "stage3x_target_relation_screen.md"
SELECTED_JSON = OUT_ROOT / "selected_feature_contracts.json"

HELDOUT_START = pd.Timestamp("2025-01-01", tz="UTC")
TIMESTAMP_COL = "DATE_TIME"
CORE_COLUMNS = {"DATE_TIME", "OPEN", "HIGH", "LOW", "CLOSE", "VOLUME"}
FORWARD_HORIZONS = (1, 3, 6)
VALIDATION_FRACTION = 0.25
MIN_ROWS = 180
MIN_SELECTED_FEATURES = 4
MIN_ABS_VAL_IC = 0.01
# Export every CPU-screened PASS contract. The smoke request worker still
# dispatches only small batches, while the guard keeps broad GPU blocked.
TOP_CONTRACT_LIMIT = None
TRANSACTION_COST_PROXY = 0.0005
MAX_MI_ROWS = 3000
BROKER_OANDA_FX = "oanda_us_fx"
BROKER_CRYPTO_SPOT = "crypto_exchange_spot"
BROKER_CRYPTO_PERP = "crypto_exchange_perp"
FX_ASSET_TOKENS = frozenset({
    "audusd", "eurusd", "gbpusd", "usdjpy", "usdcad", "usdchf", "nzdusd",
    "eurgbp", "eurjpy", "audjpy", "gbpjpy", "eurchf", "euraud", "gbpaud",
    "audcad", "audnzd", "cadjpy", "nzdjpy", "xauusd",
})
# Any column whose name matches one of these patterns is forbidden as a feature
# because it leaks the target the worker is trying to predict. ``fwd_return_*``
# is generated by ``prepare_frame``; the other prefixes/names catch upstream
# datasets that already carry a packaged target column.
LEAK_PREFIXES = ("fwd_return_", "future_", "next_return", "next_close", "target_", "label_", "y_")
LEAK_NAMES = {"target", "label", "y", "future_return", "next_return", "next_close"}
PREPROCESSING_CONTRACT_KEYS = (
    "scaling_mode",
    "feature_scaling_window",
    "feature_clip",
    "window_size",
    "stage_b_force_close_obs",
    "force_close_dow",
    "force_close_hour",
    "force_close_window_hours",
    "monday_entry_window_hours",
)


class TargetRelationError(Exception):
    """Raised when a genome cannot be safely screened."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        out = float(value)
    except Exception:
        return default
    return out if math.isfinite(out) else default


def load_population(path: Path = POPULATION_CSV) -> list[dict[str, Any]]:
    with path.open("r", newline="", encoding="utf-8") as fh:
        return [dict(row) for row in csv.DictReader(fh)]


def load_dataset(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise TargetRelationError(f"input data file missing: {path}")
    df = pd.read_csv(path)
    if TIMESTAMP_COL not in df.columns:
        raise TargetRelationError(f"missing {TIMESTAMP_COL}: {path}")
    ts = pd.to_datetime(df[TIMESTAMP_COL], utc=True, errors="raise")
    if ts.isnull().any():
        raise TargetRelationError(f"unparseable timestamps in {path}")
    if ts.duplicated().any():
        raise TargetRelationError(f"duplicate timestamps in {path}")
    if not ts.is_monotonic_increasing:
        raise TargetRelationError(f"timestamps are not monotonic in {path}")
    if (ts >= HELDOUT_START).any():
        first = str(ts[ts >= HELDOUT_START].iloc[0])
        raise TargetRelationError(f"Stage C row found in {path}: {first}")
    df = df.copy()
    df[TIMESTAMP_COL] = ts
    if "CLOSE" not in df.columns:
        raise TargetRelationError(f"missing CLOSE column: {path}")
    return df


def is_target_leak_column(col: str) -> bool:
    """Return True if ``col`` looks like a target/label rather than a feature.

    The screen builds its own ``fwd_return_*`` columns from CLOSE, but upstream
    CSVs sometimes ship a pre-baked target (e.g. ``target``, ``label``,
    ``future_return``, ``next_close``, ``y_1``). Treating such a column as a
    feature trivially "passes" the IC and proxy checks and ruins the screen.
    """
    lower = col.lower()
    if lower in LEAK_NAMES:
        return True
    return any(lower.startswith(prefix) for prefix in LEAK_PREFIXES)


def numeric_feature_columns(df: pd.DataFrame) -> list[str]:
    return [
        col for col in df.columns
        if (
            col not in CORE_COLUMNS
            and not is_target_leak_column(col)
            and pd.api.types.is_numeric_dtype(df[col])
        )
    ]


def prepare_frame(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    frame = df.copy()
    close = pd.to_numeric(frame["CLOSE"], errors="coerce")
    for horizon in FORWARD_HORIZONS:
        frame[f"fwd_return_{horizon}"] = close.shift(-horizon) / close - 1.0
    features = numeric_feature_columns(frame)
    frame = frame.replace([np.inf, -np.inf], np.nan)
    usable_cols = [TIMESTAMP_COL, "CLOSE", *features, *(f"fwd_return_{h}" for h in FORWARD_HORIZONS)]
    frame = frame[usable_cols].dropna(subset=["fwd_return_1"])
    return frame, features


def split_train_validation(frame: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    if len(frame) < MIN_ROWS:
        raise TargetRelationError(f"insufficient rows for screening: {len(frame)} < {MIN_ROWS}")
    split_at = int(len(frame) * (1.0 - VALIDATION_FRACTION))
    if split_at <= 0 or split_at >= len(frame):
        raise TargetRelationError("invalid train/validation split")
    train = frame.iloc[:split_at].copy()
    validation = frame.iloc[split_at:].copy()
    if train[TIMESTAMP_COL].max() >= validation[TIMESTAMP_COL].min():
        raise TargetRelationError("train/validation split overlaps or is not chronological")
    return train, validation


def spearman_ic(x: pd.Series, y: pd.Series) -> float:
    aligned = pd.concat([x, y], axis=1).dropna()
    if len(aligned) < 20:
        return 0.0
    if aligned.iloc[:, 0].nunique() <= 1 or aligned.iloc[:, 1].nunique() <= 1:
        return 0.0
    val = scipy_stats.spearmanr(aligned.iloc[:, 0], aligned.iloc[:, 1]).correlation
    return safe_float(val)


def mutual_info_score(x: pd.Series, y: pd.Series) -> float:
    aligned = pd.concat([x, y], axis=1).dropna()
    if len(aligned) < 40 or aligned.iloc[:, 0].nunique() <= 1:
        return 0.0
    if len(aligned) > MAX_MI_ROWS:
        idx = np.linspace(0, len(aligned) - 1, MAX_MI_ROWS).astype(int)
        aligned = aligned.iloc[idx]
    values = aligned.iloc[:, 0].to_numpy(dtype=float).reshape(-1, 1)
    target = aligned.iloc[:, 1].to_numpy(dtype=float)
    try:
        score = mutual_info_regression(values, target, random_state=42, n_neighbors=5)[0]
    except Exception:
        return 0.0
    return safe_float(score)


def feature_quality(train: pd.DataFrame, validation: pd.DataFrame, feature: str) -> dict[str, Any]:
    combined = pd.concat([train[[feature]], validation[[feature]]], axis=0)
    missing_fraction = float(combined[feature].isna().mean())
    n_unique = int(combined[feature].nunique(dropna=True))
    std = safe_float(combined[feature].std())
    is_constant = n_unique <= 1 or std <= 1e-12
    train_ic = spearman_ic(train[feature], train["fwd_return_1"])
    val_ic = spearman_ic(validation[feature], validation["fwd_return_1"])
    val_ic_3 = spearman_ic(validation[feature], validation["fwd_return_3"])
    val_ic_6 = spearman_ic(validation[feature], validation["fwd_return_6"])
    mi = mutual_info_score(train[feature], train["fwd_return_1"])
    sign_stable = bool(train_ic == 0.0 or val_ic == 0.0 or np.sign(train_ic) == np.sign(val_ic))
    stability_penalty = abs(abs(train_ic) - abs(val_ic))
    score = (
        abs(val_ic)
        + 0.5 * abs(val_ic_3)
        + 0.25 * abs(val_ic_6)
        + min(mi, 0.05)
        + (0.01 if sign_stable else -0.02)
        - 0.25 * stability_penalty
        - (0.25 if is_constant else 0.0)
        - min(missing_fraction, 0.5)
    )
    return {
        "feature": feature,
        "missing_fraction": missing_fraction,
        "n_unique": n_unique,
        "std": std,
        "is_constant": is_constant,
        "train_ic_1": train_ic,
        "validation_ic_1": val_ic,
        "validation_ic_3": val_ic_3,
        "validation_ic_6": val_ic_6,
        "mutual_info_train": mi,
        "sign_stable": sign_stable,
        "feature_score": safe_float(score),
    }


def regime_conditioned_score(validation: pd.DataFrame, feature: str) -> float:
    returns = validation["fwd_return_1"].abs()
    if len(returns.dropna()) < 40:
        return 0.0
    cutoff = returns.median()
    low = validation[returns <= cutoff]
    high = validation[returns > cutoff]
    if len(low) < 20 or len(high) < 20:
        return 0.0
    return 0.5 * (
        abs(spearman_ic(low[feature], low["fwd_return_1"]))
        + abs(spearman_ic(high[feature], high["fwd_return_1"]))
    )


def select_features(
    qualities: list[dict[str, Any]],
    validation: pd.DataFrame,
    *,
    method: str,
    budget: int,
    regime_cache: dict[str, float] | None = None,
) -> list[dict[str, Any]]:
    rows = [row for row in qualities if not row["is_constant"] and row["missing_fraction"] <= 0.25]
    if method == "rank_ic_topk":
        key = lambda row: (abs(row["validation_ic_1"]), row["feature_score"])
    elif method == "mutual_info_topk":
        key = lambda row: (row["mutual_info_train"], row["feature_score"])
    elif method == "regime_conditioned_topk":
        # Reuse the per-dataset cache so the (slow) regime-split spearman pair
        # is computed once per feature across all genomes that share the file.
        for row in rows:
            feature = row["feature"]
            if regime_cache is not None and feature in regime_cache:
                row["regime_conditioned_ic"] = regime_cache[feature]
            else:
                score = regime_conditioned_score(validation, feature)
                row["regime_conditioned_ic"] = score
                if regime_cache is not None:
                    regime_cache[feature] = score
        key = lambda row: (row.get("regime_conditioned_ic", 0.0), row["feature_score"])
    else:
        key = lambda row: (row["feature_score"], abs(row["validation_ic_1"]))
    return sorted(rows, key=key, reverse=True)[:max(1, budget)]


def threshold_sanity(validation: pd.DataFrame, selected: list[dict[str, Any]]) -> dict[str, Any]:
    if not selected:
        return {"proxy_net_return": 0.0, "proxy_trades": 0, "proxy_exposure": 0.0}
    feature = selected[0]["feature"]
    sign = 1.0 if selected[0]["validation_ic_1"] >= 0 else -1.0
    series = validation[feature].astype(float)
    z = (series - series.median()) / (series.mad() if hasattr(series, "mad") else series.sub(series.median()).abs().median())
    z = z.replace([np.inf, -np.inf], np.nan).fillna(0.0)
    threshold = float(z.abs().quantile(0.75))
    position = np.where(z * sign > threshold, 1.0, np.where(z * sign < -threshold, -1.0, 0.0))
    fwd = validation["fwd_return_1"].fillna(0.0).to_numpy(dtype=float)
    changes = np.abs(np.diff(position, prepend=0.0)) > 0
    net = position * fwd - changes.astype(float) * TRANSACTION_COST_PROXY
    return {
        "proxy_net_return": safe_float(np.nansum(net)),
        "proxy_mean_return": safe_float(np.nanmean(net)),
        "proxy_trades": int(changes.sum()),
        "proxy_exposure": safe_float(np.mean(position != 0.0)),
        "proxy_feature": feature,
    }


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def broker_metadata_for_asset(asset: Any, timeframe: Any) -> dict[str, str]:
    """Return explicit broker/market metadata for a selected contract."""
    asset_token = str(asset or "").lower()
    tf = str(timeframe or "").lower()
    if asset_token.endswith("_perp"):
        broker_profile = BROKER_CRYPTO_PERP
        market_type = "crypto_perp"
        regulatory_profile = "none_or_external"
    elif asset_token in FX_ASSET_TOKENS:
        broker_profile = BROKER_OANDA_FX
        market_type = "fx"
        regulatory_profile = "cftc_nfa_retail_forex"
    elif asset_token.endswith("usdt"):
        # USDT-quoted spot symbols are exchange spot data, not OANDA spot crypto
        # instruments. OANDA crypto uses fiat-quoted symbols and has different
        # long-only/no-leverage/fee constraints.
        broker_profile = BROKER_CRYPTO_SPOT
        market_type = "crypto_spot"
        regulatory_profile = "none_or_external"
    else:
        broker_profile = "broker_profile_unconfirmed"
        market_type = "market_type_unconfirmed"
        regulatory_profile = "none_or_external"
    return {
        "broker_profile": broker_profile,
        "market_type": market_type,
        "regulatory_profile": regulatory_profile,
        "trade_rate_band_id": f"{broker_profile}_{tf}" if broker_profile and tf else "",
    }


def prepare_dataset(path: Path) -> dict[str, Any]:
    df = load_dataset(path)
    frame, features = prepare_frame(df)
    train, validation = split_train_validation(frame)
    qualities = [feature_quality(train, validation, feature) for feature in features]
    return {
        "frame": frame,
        "features": features,
        "train": train,
        "validation": validation,
        "qualities": qualities,
        # Caches reused across every genome that points at the same input file.
        # ``regime_cache`` holds the per-feature regime-conditioned score; the
        # MI / IC values already live in ``qualities`` and are copied per genome.
        "regime_cache": {},
        "data_file_sha256": sha256_file(path) if path.exists() else "",
    }


def screen_prepared_genome(genome: dict[str, Any], prepared: dict[str, Any]) -> dict[str, Any]:
    frame = prepared["frame"]
    features = prepared["features"]
    train = prepared["train"]
    validation = prepared["validation"]
    qualities = [dict(row) for row in prepared["qualities"]]
    regime_cache = prepared.setdefault("regime_cache", {})
    budget = int(float(genome.get("feature_budget") or 16))
    method = str(genome.get("feature_selection_method") or "corr_stability_topk")
    selected = select_features(
        qualities, validation, method=method, budget=budget, regime_cache=regime_cache
    )
    sanity = threshold_sanity(validation, selected)
    best_ic = max((abs(row["validation_ic_1"]) for row in selected), default=0.0)
    stable_count = sum(1 for row in selected if row.get("sign_stable"))
    constant_count = sum(1 for row in qualities if row["is_constant"])
    score = (
        sum(max(0.0, row["feature_score"]) for row in selected[:8])
        + max(0.0, sanity["proxy_net_return"])
        + 0.01 * stable_count
        - 0.001 * constant_count
    )
    status = "PASS_CPU_SCREEN"
    blockers: list[str] = []
    if len(selected) < MIN_SELECTED_FEATURES:
        blockers.append("TOO_FEW_SELECTED_FEATURES")
    if best_ic < MIN_ABS_VAL_IC:
        blockers.append("WEAK_VALIDATION_IC")
    if sanity["proxy_trades"] <= 0:
        blockers.append("NO_THRESHOLD_TRADES")
    if sanity["proxy_net_return"] <= 0.0:
        blockers.append("NEGATIVE_COST_AWARE_PROXY_RETURN")
    if not blockers:
        status = "PASS_CPU_SCREEN"
    else:
        status = "WATCH_CPU_SCREEN" if best_ic >= MIN_ABS_VAL_IC else "FAIL_CPU_SCREEN"
    return {
        "genome_id": genome.get("genome_id"),
        "asset": genome.get("asset"),
        "timeframe": genome.get("timeframe"),
        "feature_preset": genome.get("feature_preset"),
        "source_family": genome.get("source_family"),
        "feature_selection_method": method,
        "preprocessing_profile": genome.get("preprocessing_profile"),
        **{key: genome.get(key) for key in PREPROCESSING_CONTRACT_KEYS if key in genome},
        "input_data_file": genome.get("input_data_file"),
        "data_file_sha256": str(prepared.get("data_file_sha256") or ""),
        "n_rows": int(len(frame)),
        "train_rows": int(len(train)),
        "validation_rows": int(len(validation)),
        "feature_count_available": int(len(features)),
        "constant_feature_count": int(constant_count),
        "selected_feature_count": int(len(selected)),
        "best_abs_validation_ic": safe_float(best_ic),
        "stable_selected_feature_count": int(stable_count),
        "screen_score": safe_float(score),
        "status": status,
        "blockers": blockers,
        "stage_c_access": "DENIED",
        "training_launched": False,
        **sanity,
        "selected_features": [row["feature"] for row in selected],
        "top_feature_metrics": selected[:10],
    }


def screen_genome(genome: dict[str, Any]) -> dict[str, Any]:
    prepared = prepare_dataset(Path(str(genome["input_data_file"])))
    return screen_prepared_genome(genome, prepared)


def write_outputs(rows: list[dict[str, Any]], selected_contracts: list[dict[str, Any]]) -> dict[str, Any]:
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    pass_count = sum(1 for row in rows if row["status"] == "PASS_CPU_SCREEN")
    payload = {
        "schema_version": "project3_stage3x_target_relation_screen_v1",
        "generated_at": utc_now(),
        "heldout_start": "2025-01-01",
        "stage_c_access": "DENIED",
        "training_launched": False,
        "genome_count": len(rows),
        "pass_cpu_screen": pass_count,
        "watch_or_fail": len(rows) - pass_count,
        "selected_contract_count": len(selected_contracts),
        "rows": rows,
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
    contracts_payload = {
        "schema_version": "project3_stage3x_selected_feature_contracts_v1",
        "generated_at": payload["generated_at"],
        "stage_c_access": "DENIED",
        "training_launched": False,
        "contracts": selected_contracts,
    }
    SELECTED_JSON.write_text(
        json.dumps(contracts_payload, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    csv_fields = [
        "genome_id", "asset", "timeframe", "feature_preset", "source_family",
        "feature_selection_method", "preprocessing_profile", "n_rows",
        "feature_count_available", "constant_feature_count", "selected_feature_count",
        "best_abs_validation_ic", "stable_selected_feature_count", "proxy_net_return",
        "proxy_trades", "proxy_exposure", "screen_score", "status", "blockers",
    ]
    with OUT_CSV.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=csv_fields)
        writer.writeheader()
        for row in rows:
            slim = {field: row.get(field) for field in csv_fields}
            slim["blockers"] = ";".join(row.get("blockers") or [])
            writer.writerow(slim)
    lines = [
        "# Stage 3X Target-Relation Screen",
        "",
        f"Generated UTC: `{payload['generated_at']}`",
        "",
        f"- Stage C access: `{payload['stage_c_access']}`",
        f"- Training launched: `{payload['training_launched']}`",
        f"- Genomes screened: `{payload['genome_count']}`",
        f"- PASS CPU screen: `{payload['pass_cpu_screen']}`",
        f"- Selected contracts: `{payload['selected_contract_count']}`",
        "",
        "## Top Contracts",
        "",
        "| rank | genome | asset | timeframe | preset | method | score | best IC | proxy return | trades |",
        "| ---: | --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for idx, row in enumerate(selected_contracts, start=1):
        lines.append(
            f"| {idx} | `{row['genome_id']}` | `{row['asset']}` | `{row['timeframe']}` | "
            f"`{row['feature_preset']}` | `{row['feature_selection_method']}` | "
            f"{row['screen_score']:.6f} | {row['best_abs_validation_ic']:.6f} | "
            f"{row['proxy_net_return']:.6f} | {row['proxy_trades']} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return payload


def main() -> None:
    population = load_population()
    rows: list[dict[str, Any]] = []
    prepared_cache: dict[str, dict[str, Any]] = {}
    for genome in population:
        try:
            input_path = str(genome["input_data_file"])
            if input_path not in prepared_cache:
                prepared_cache[input_path] = prepare_dataset(Path(input_path))
            rows.append(screen_prepared_genome(genome, prepared_cache[input_path]))
        except Exception as exc:
            rows.append(
                {
                    "genome_id": genome.get("genome_id"),
                    "asset": genome.get("asset"),
                    "timeframe": genome.get("timeframe"),
                    "feature_preset": genome.get("feature_preset"),
                    "source_family": genome.get("source_family"),
                    "feature_selection_method": genome.get("feature_selection_method"),
                    "preprocessing_profile": genome.get("preprocessing_profile"),
                    "input_data_file": genome.get("input_data_file"),
                    "status": "ERROR",
                    "blockers": [type(exc).__name__],
                    "error": str(exc),
                    "stage_c_access": "DENIED",
                    "training_launched": False,
                    "screen_score": -1.0,
                    "selected_features": [],
                    "top_feature_metrics": [],
                }
            )
    ranked = sorted(
        [row for row in rows if row.get("status") == "PASS_CPU_SCREEN"],
        key=lambda row: row.get("screen_score", -1.0),
        reverse=True,
    )
    selected_contracts = []
    selected_rows = ranked if TOP_CONTRACT_LIMIT is None else ranked[:TOP_CONTRACT_LIMIT]
    for row in selected_rows:
        broker_metadata = broker_metadata_for_asset(row["asset"], row["timeframe"])
        selected_contracts.append(
            {
                "contract_id": f"{row['genome_id']}__selected",
                "genome_id": row["genome_id"],
                "asset": row["asset"],
                "timeframe": row["timeframe"],
                "feature_preset": row["feature_preset"],
                "source_family": row["source_family"],
                "feature_selection_method": row["feature_selection_method"],
                "preprocessing_profile": row["preprocessing_profile"],
                **{key: row.get(key) for key in PREPROCESSING_CONTRACT_KEYS if key in row},
                "input_data_file": row["input_data_file"],
                "data_file_sha256": row.get("data_file_sha256", ""),
                "selected_features": row["selected_features"],
                "selected_feature_count": row["selected_feature_count"],
                "best_abs_validation_ic": row["best_abs_validation_ic"],
                "proxy_net_return": row["proxy_net_return"],
                "proxy_trades": row["proxy_trades"],
                "screen_score": row["screen_score"],
                **broker_metadata,
                "stage_c_access": "DENIED",
                "training_launched": False,
            }
        )
    payload = write_outputs(rows, selected_contracts)
    print(
        json.dumps(
            {
                "ok": True,
                "genome_count": payload["genome_count"],
                "pass_cpu_screen": payload["pass_cpu_screen"],
                "selected_contract_count": payload["selected_contract_count"],
                "selected_json": str(SELECTED_JSON),
                "summary_md": str(OUT_MD),
                "training_launched": False,
                "stage_c_access": "DENIED",
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
