from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path("/home/harveybc/Documents/GitHub/financial-data")
LOG = ROOT / "_logs" / "omega" / "stage13_doc_backfill_worker.log"
SCAN_ROOTS = [
    "market_data",
    "macro_economic",
    "alternative_data",
    "reference_data",
    "economic_calendar",
]
DATA_SUFFIXES = {".parquet", ".csv", ".json", ".jsonl", ".zip"}
DOC_NAMES = {"README.md", "data_dictionary.md", "provenance.json"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def log(message: str) -> None:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    with LOG.open("a", encoding="utf-8") as f:
        f.write(f"{utc_now()} {message}\n")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def data_directories() -> list[Path]:
    folders: set[Path] = set()
    for root_name in SCAN_ROOTS:
        root = ROOT / root_name
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if path.name in DOC_NAMES:
                continue
            if path.suffix.lower() in DATA_SUFFIXES:
                folders.add(path.parent)
    return sorted(folders)


def backfill_folder(folder: Path) -> bool:
    missing = [name for name in DOC_NAMES if not (folder / name).exists()]
    if not missing:
        return False

    data_files = sorted(
        path for path in folder.iterdir()
        if path.is_file() and path.name not in DOC_NAMES and path.suffix.lower() in DATA_SUFFIXES
    )
    if not data_files:
        return False

    if not (folder / "README.md").exists():
        (folder / "README.md").write_text(
            f"# {folder.name}\n\n"
            "Autogenerated Stage 1.3 documentation for an acquired data directory that was missing "
            "standard README/data dictionary/provenance files.\n\n"
            "Source details should be cross-checked against `_metadata/acquisition_log.csv` and the "
            "corresponding worker logs under `_logs/`.\n",
            encoding="utf-8",
        )

    if not (folder / "data_dictionary.md").exists():
        (folder / "data_dictionary.md").write_text(
            "# Data Dictionary\n\n"
            "Columns and file structure follow the upstream source or the source-specific acquisition "
            "worker output. This file was autogenerated as documentation coverage, not as a semantic "
            "schema guarantee.\n",
            encoding="utf-8",
        )

    if not (folder / "provenance.json").exists():
        provenance = {
            "source": "autogenerated_stage13_doc_backfill",
            "description": "Documentation coverage backfill for existing Stage 1.3 acquired files.",
            "documented_at": utc_now(),
            "folder": rel(folder),
            "files": [
                {
                    "path": rel(path),
                    "bytes": path.stat().st_size,
                    "sha256": sha256_file(path),
                }
                for path in data_files
            ],
        }
        (folder / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")

    return True


def main() -> None:
    log("START omega documentation backfill worker")
    updated: list[str] = []
    for folder in data_directories():
        if backfill_folder(folder):
            updated.append(rel(folder))
            log(f"backfilled docs {rel(folder)}")
    log(f"DONE omega documentation backfill worker updated_dirs={len(updated)}")


if __name__ == "__main__":
    main()
