from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(os.environ.get("PROJECT3_ROOT", "/home/harveybc/Documents/GitHub/financial-data"))
TARGET_TIMEFRAMES = ("5m", "15m", "1h", "4h")
FREQ = {"5m": "5min", "15m": "15min", "1h": "1h", "4h": "4h"}
TIMESTAMP_COLUMNS = (
    "timestamp",
    "datetime",
    "date",
    "Date",
    "time",
    "open_time",
    "fundingTime",
    "announcement_datetime_utc",
    "period",
)
SKIP_PARTS = {"trading_asset_data", "sec_filings"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def slugify(path: Path) -> str:
    raw = rel(path.with_suffix(""))
    raw = raw.replace("/", "__")
    raw = re.sub(r"[^a-zA-Z0-9_]+", "_", raw).strip("_").lower()
    return raw[:180]


def log(machine: str, message: str) -> None:
    path = ROOT / "_logs" / machine / "stage21_cross_source_worker.log"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(f"{utc_now()} {message}\n")


def notify(event: str, title: str, message: str) -> None:
    script = ROOT / "_scripts" / "telegram_notify.py"
    if not script.exists():
        return
    import subprocess
    import sys

    try:
        subprocess.run(
            [
                sys.executable,
                str(script),
                "--event",
                f"stage21:cross:{event}",
                "--title",
                title,
                "--message",
                message,
                "--min-interval-minutes",
                "20",
            ],
            cwd=ROOT,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=20,
            check=False,
        )
    except Exception:
        return


def discover_sources(roots: list[str]) -> list[Path]:
    out: list[Path] = []
    for raw in roots:
        root = ROOT / raw
        if not root.exists():
            continue
        for path in sorted(root.rglob("*.parquet")):
            if any(part in SKIP_PARTS for part in path.parts):
                continue
            out.append(path)
    return out


def normalize_timeseries(path: Path) -> tuple[pd.DataFrame | None, str]:
    try:
        df = pd.read_parquet(path)
    except Exception as exc:
        return None, f"read_failed:{type(exc).__name__}:{exc}"
    if df.empty:
        return None, "empty"
    timestamp_col = next((col for col in TIMESTAMP_COLUMNS if col in df.columns), None)
    if timestamp_col is None and isinstance(df.index, pd.DatetimeIndex):
        df = df.reset_index().rename(columns={df.index.name or "index": "timestamp"})
        timestamp_col = "timestamp"
    if timestamp_col is None:
        return None, "no_timestamp_column"
    out = df.copy()
    out["timestamp"] = pd.to_datetime(out[timestamp_col], utc=True, errors="coerce").astype("datetime64[ns, UTC]")
    out = out.dropna(subset=["timestamp"]).sort_values("timestamp")
    if out.empty:
        return None, "no_valid_timestamps"
    numeric_cols = []
    for col in out.columns:
        if col == "timestamp" or col == timestamp_col:
            continue
        converted = pd.to_numeric(out[col], errors="coerce")
        if converted.notna().sum() >= max(2, int(len(out) * 0.05)):
            out[col] = converted
            numeric_cols.append(col)
    if not numeric_cols:
        return None, "no_numeric_columns"
    out = out[["timestamp", *numeric_cols]].drop_duplicates(subset=["timestamp"], keep="last")
    return out, "ok"


def forward_fill(df: pd.DataFrame, tf: str) -> pd.DataFrame:
    start = df["timestamp"].min().floor(FREQ[tf])
    end = df["timestamp"].max().ceil(FREQ[tf])
    grid = pd.DataFrame({"timestamp": pd.date_range(start=start, end=end, freq=FREQ[tf], tz="UTC")})
    source = df.sort_values("timestamp").copy()
    source["timestamp"] = pd.to_datetime(source["timestamp"], utc=True, errors="coerce").astype("datetime64[ns, UTC]")
    merged = pd.merge_asof(
        grid,
        source,
        on="timestamp",
        direction="backward",
        allow_exact_matches=True,
    )
    return merged


def write_source_docs(source: Path, slug: str, status: dict[str, Any]) -> None:
    doc_dir = ROOT / "features" / "cross_source_docs" / slug
    doc_dir.mkdir(parents=True, exist_ok=True)
    (doc_dir / "README.md").write_text(
        "\n".join(
            [
                f"# Stage 2.1 Cross-Source Input: {slug}",
                "",
                f"Source: `{rel(source)}`",
                "",
                "Generated by point-in-time forward fill onto 5m, 15m, 1h, and 4h grids.",
                "No interpolation is used. Each target timestamp receives the latest value known at or before that timestamp.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (doc_dir / "data_dictionary.md").write_text(
        "\n".join(
            [
                "# Data Dictionary",
                "",
                "- `timestamp`: UTC target-grid timestamp.",
                "- Other columns: numeric source values preserved from the raw Phase 1 source.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (doc_dir / "provenance.json").write_text(json.dumps(status, indent=2) + "\n", encoding="utf-8")


def process_source(source: Path, machine: str) -> dict[str, Any]:
    slug = slugify(source)
    df, status = normalize_timeseries(source)
    result: dict[str, Any] = {
        "source": rel(source),
        "slug": slug,
        "status": status,
        "timeframes": {},
    }
    if df is None:
        log(machine, f"skip source={rel(source)} reason={status}")
        return result
    result.update(
        {
            "status": "ok",
            "rows_native": int(len(df)),
            "columns": [col for col in df.columns if col != "timestamp"],
            "start": df["timestamp"].min().isoformat(),
            "end": df["timestamp"].max().isoformat(),
        }
    )
    for tf in TARGET_TIMEFRAMES:
        try:
            out = forward_fill(df, tf)
            out_dir = ROOT / "features" / "cross_source_features" / tf
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / f"{slug}.parquet"
            out.to_parquet(out_path, index=False)
            result["timeframes"][tf] = {
                "path": rel(out_path),
                "rows": int(len(out)),
                "missing_pct": float(out.drop(columns=["timestamp"]).isna().all(axis=1).mean()) if len(out) else 1.0,
            }
        except Exception as exc:
            result["timeframes"][tf] = {
                "status": "failed",
                "error": f"{type(exc).__name__}: {exc}",
            }
    write_source_docs(source, slug, result)
    log(machine, f"source={rel(source)} slug={slug} rows={len(df)}")
    return result


def write_report(machine: str, results: list[dict[str, Any]]) -> None:
    ok = [result for result in results if result.get("status") == "ok"]
    skipped = [result for result in results if result.get("status") != "ok"]
    summary = {
        "generated_at": utc_now(),
        "stage": "Stage 2.1",
        "machine": machine,
        "sources_total": len(results),
        "sources_processed": len(ok),
        "sources_skipped": len(skipped),
        "timeframe_outputs": sum(len(item.get("timeframes", {})) for item in ok),
        "skip_reasons": {},
        "results": results,
    }
    reasons: dict[str, int] = {}
    for item in skipped:
        reasons[item.get("status", "unknown")] = reasons.get(item.get("status", "unknown"), 0) + 1
    summary["skip_reasons"] = reasons
    out_json = ROOT / "_metadata" / f"stage21_cross_source_{machine}.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    out_md = ROOT / "_logs" / "supervisor_reports" / f"stage21_cross_source_{machine}.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Stage 2.1 Cross-Source Forward Fill - {machine}",
        "",
        f"Generated: {summary['generated_at']}",
        "",
        f"- Sources total: {summary['sources_total']}",
        f"- Sources processed: {summary['sources_processed']}",
        f"- Sources skipped: {summary['sources_skipped']}",
        f"- Timeframe outputs: {summary['timeframe_outputs']}",
        f"- Skip reasons: {json.dumps(reasons, sort_keys=True)}",
    ]
    out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--machine", default="gamma")
    parser.add_argument("--roots", nargs="+", required=True)
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    log(args.machine, f"START stage21 cross-source roots={args.roots} limit={args.limit}")
    notify(
        f"{args.machine}:start",
        f"Project 3 Stage 2.1 {args.machine} cross-source started",
        f"machine: {args.machine}\nstage: Stage 2.1\ncurrent_task: cross-source point-in-time forward-fill\nexpected_deliverable: features/cross_source_features; _metadata/stage21_cross_source_{args.machine}.json",
    )
    sources = discover_sources(args.roots)
    if args.limit:
        sources = sources[: args.limit]
    results = [process_source(source, args.machine) for source in sources]
    write_report(args.machine, results)
    log(args.machine, f"DONE stage21 cross-source sources={len(results)}")
    notify(
        f"{args.machine}:finish",
        f"Project 3 Stage 2.1 {args.machine} cross-source finished",
        f"machine: {args.machine}\nstage: Stage 2.1\nstatus: finished\ndeliverable_path: _metadata/stage21_cross_source_{args.machine}.json\nsources: {len(results)}",
    )


if __name__ == "__main__":
    main()
